sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abcddd\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":99, \"username\":\"aaa\",\"password\":\"111\"},{\"id\":101, \"username\":\"git\",\"password\":\"gitpass\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.176.131
    port: 5672
    username: admin
    password: admin 
    
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
        
#test check out     
